"""
api/grpc/server.py — gRPC server with streaming query support.

Requires: pip install grpcio grpcio-tools
Generate stubs: make proto
"""
from __future__ import annotations

import asyncio
import json
import uuid
from typing import AsyncIterator

import structlog

logger = structlog.get_logger(__name__)

# These are generated by: make proto
# If not yet generated, the server gracefully reports the error
try:
    import api.grpc.rag_service_pb2 as pb2  # type: ignore
    import api.grpc.rag_service_pb2_grpc as pb2_grpc  # type: ignore
    GRPC_STUBS_AVAILABLE = True
except ImportError:
    GRPC_STUBS_AVAILABLE = False
    logger.warning("grpc_stubs_not_generated", msg="Run: make proto")


class RAGServicer:
    """Implements the RAGService gRPC interface."""

    async def Query(
        self, request: Any, context: Any  # type: ignore
    ) -> AsyncIterator[Any]:
        """
        Streaming query: runs the RAG pipeline and yields tokens
        as they're generated. Final chunk has is_final=True and full answer.
        """
        if not GRPC_STUBS_AVAILABLE:
            raise RuntimeError("gRPC stubs not generated. Run: make proto")

        from core.config import settings

        # Auth check
        if request.api_key != settings.api_key:
            await context.abort(16, "Unauthenticated: invalid API key")
            return

        trace_id = str(uuid.uuid4())
        query = request.query
        pipeline = request.pipeline or "auto"

        logger.info("grpc_query", query=query[:60], pipeline=pipeline, trace_id=trace_id)

        from orchestrator.graph import get_orchestrator
        orchestrator = get_orchestrator()

        # Yield progress tokens
        yield pb2.QueryResponse(
            trace_id=trace_id,
            pipeline_used=pipeline,
            token="[Retrieving relevant information...]",
            is_final=False,
        )

        try:
            result = await orchestrator.run(
                query=query,
                mode=pipeline,  # type: ignore
                session_id=request.session_id or None,
            )
            answer = result.get("final_answer", "")
            usage = result.get("token_usage", {})

            # Stream answer word by word (simulate streaming)
            words = answer.split()
            for word in words[:-1]:
                yield pb2.QueryResponse(
                    trace_id=trace_id,
                    pipeline_used=result.get("pipeline_used", pipeline),
                    token=word + " ",
                    is_final=False,
                )
                await asyncio.sleep(0)  # yield control

            # Final chunk
            yield pb2.QueryResponse(
                trace_id=trace_id,
                pipeline_used=result.get("pipeline_used", pipeline),
                token=words[-1] if words else "",
                final_answer=answer,
                is_final=True,
                token_usage=usage,
                latency_ms=result.get("comparison_metrics", {}).get("total_latency_ms", 0),
            )

        except Exception as exc:
            logger.error("grpc_query_error", error=str(exc), trace_id=trace_id)
            yield pb2.QueryResponse(
                trace_id=trace_id,
                token=f"Error: {exc}",
                is_final=True,
            )

    async def GetTrace(self, request: Any, context: Any) -> Any:  # type: ignore
        """Retrieve a full execution trace by ID."""
        if not GRPC_STUBS_AVAILABLE:
            raise RuntimeError("gRPC stubs not generated.")

        from api.rest.app import _trace_store
        from core.config import settings

        if request.api_key != settings.api_key:
            await context.abort(16, "Unauthenticated")
            return

        trace = _trace_store.get(request.trace_id)
        if not trace:
            await context.abort(5, f"Trace {request.trace_id} not found")
            return

        return pb2.TraceResponse(
            trace_id=request.trace_id,
            query=trace.get("query", ""),
            pipeline=trace.get("pipeline", ""),
            raw_json=json.dumps(trace, default=str),
        )


async def serve() -> None:
    """Start the gRPC server."""
    if not GRPC_STUBS_AVAILABLE:
        logger.error("Cannot start gRPC server: stubs not generated. Run: make proto")
        return

    import grpc
    from core.config import settings
    from observability.logging import setup_logging
    from observability.tracing import setup_tracing, setup_langsmith

    setup_logging()
    setup_tracing()
    setup_langsmith()

    server = grpc.aio.server()
    pb2_grpc.add_RAGServiceServicer_to_server(RAGServicer(), server)
    addr = f"[::]:{settings.grpc_port}"
    server.add_insecure_port(addr)
    await server.start()
    logger.info("grpc_server_started", addr=addr)
    await server.wait_for_termination()


if __name__ == "__main__":
    from typing import Any  # noqa: F811
    asyncio.run(serve())
